### ISSUE TITLE
Show actual transformations taking place

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/search-replace-command#1]
From https://github.com/wp-cli/wp-cli/issues/3777

> There should be a way to see the changes that a search-replace would make. This would be especially valuable to use with `--regex` flag, where your changes can get out of control if you don't see what's going on.
>
> The current export feature is a bit underpowered because it generates a huge SQL file for the site. There's no easy way to see what exactly is changing.
>
> I think we need a report feature that generates a from/to report for each table (that's changing). I would suggest using something like WP's built-in Text Diff or PHP-diff for a diff column.
>
> There are lots of false-positives. For example, plugins that have had their PHP classes change (new properties). The unserialize will add with the newer properties from the PHP class. It will be "incorrectly" reported as a replacement. This is probably unavoidable since this has to happen at some point. However, number 1 (above) could alleviate the confusion from this.
>
> [...]
>
> The summary is not sufficient. It raises eyebrows for falsepositives (rare case though). I'm always wary of what it is going to replace before I execute the replace.
>
> The idea is coming from in-house BU search-replace script that does diffs using php-diff and outputs them into CSV files. It lacks regex searching. We're in the mode to adopt wp-cli more in the future, hence the feature request.

**Comment by danielbachhuber** [comment]
> Also I think a new command `search` should be added here for convenience which just defaults the `<new>` arg to null and sets the `--dry-run` option to true and the new log option to true (unless already set).

My preference would be to focus on `wp db ack` for now, until it can be established the `search` command fills a distinct need. Difference use cases around the same feature are better solved with documentation.

**Comment by gitlost** [comment]
Okay, will leave it out. Do you think `[--log[=<file>]]` is the right approach? Would also add supporting options like `[[--log-context=<num_words>]]` or similar.

**Comment by danielbachhuber** [comment]
> Do you think `[--log[=<file>]]` is the right approach?

Not particularly. I'd display to STDOUT, which gives the user more control over where the data ends up.

**Comment by gitlost** [comment]
I mean for it to behave like `[--export=[<file>]]`, so a simple `--log` would go to STDOUT.

**Comment by danielbachhuber** [comment]
Now that we have `wp db search`, can we close this issue?

I'm not sure it's realistic to produce a visual report of the transformations taking place; this seems more effort than it's worth.

Instead, it'd be good to know what use case isn't already solved by `wp db search`.

**Comment by gitlost** [comment]
Here's a prototype output:

![prototype_log](https://user-images.githubusercontent.com/481982/29791658-a35d4cd0-8c35-11e7-89c1-7c98f246c54f.png)

**Comment by danielbachhuber** [comment]
Huh. That's not awful then, I suppose.
