### ISSUE TITLE
Clarify "please flush object cache" message in multisite

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/search-replace-command#12]
After running `search-replace` on multisite with a persistent object cache enabled, you can see a message like this:

```
Success: Made 2419 replacements. Please remember to flush your persistent object cache with `wp cache flush`
```

However, running `wp cache flush` may produce a "Error: site not found" message if the old lookup value is still in cache.

Et voila! You've entered an indeterminate state where you'd expect you could flush cache against the new URL, but the cache still has the old URL, so you need to flush cache against the old URL before the new URL works.

We should clarify the message accordingly when this scenario occurs.

**Comment by Sidsector9** [comment]
@danielbachhuber Would a message like this be valid?

"Success: Made 2419 replacements. Please remember to flush your persistent object cache with `wp cache flush`. Make sure to as well flush the old URLs to avoid errors similar to site not found."

**Comment by danielbachhuber** [comment]
@Sidsector9 Instead of:

> Make sure you also flush the old URLs to avoid errors similar to site not found.

What about this?

> If you see a "Site not found" error after replacing a domain, try flushing cache against the old domain (which may be the cached lookup value).

**Comment by Sidsector9** [comment]
@danielbachhuber Is it possible that some error other than 'Site not found' may occur? If not then I think ^this will do.

**Comment by danielbachhuber** [comment]
> Is it possible that some error other than 'Site not found' may occur?

I don't believe so, no.
