### ISSUE TITLE
Add option to only show count

### ISSUE THREAD

**Issue by cjhaas** [wp-cli/search-replace-command#13]
I'm trying to use this in an automated workflow for moving sites between various environments (live/dev/stage) and it would be really nice to get _only_ the count of replacements for reporting purposes, something like `--display-count-only`. Right now I'm just grepping for the `Success` line which isn't the end of the world, just not the best solution.

I could create a quick PR for this, something like the below to be placed right before the [table code](https://github.com/wp-cli/search-replace-command/blob/master/src/Search_Replace_Command.php#L234)

```php
if ( \WP_CLI\Utils\get_flag_value( $assoc_args, 'display-count-only' ) ) {
    WP_CLI::line( $total );
    return;
}
```

The option `--quite` would obviously have precedence over this and this would also be compatible with `--dry-run`.

**Comment by danielbachhuber** [comment]
Seems reasonable. The existing pattern we have for this is `--format=count`, although we'd want to make sure to suppress the log output too.

**Comment by cjhaas** [comment]
Thanks! Would it makes sense then to have two formats, `table` and `count` with `table` being the default?

**Comment by danielbachhuber** [comment]
> Would it makes sense then to have two formats, table and count with table being the default?

Possibly, although the existing format is really log + table.

**Comment by danielbachhuber** [comment]
Actually, I took a look through the codebase because I thought there was an instance of this before. `wp (theme|plugin) update` produces log + table output, and calls it 'table' format. So `--format=(table|count)` would be fine.
