### ISSUE TITLE
How do I pull a report that shows every occurrence of specific word in my posts and pages?

### ISSUE THREAD

**Issue by paola-palooza** [wp-cli/search-replace-command#143]
I need to replace an outdated product name in every location on my website. But first, I want to see where this outdated product name exists or occurs. I have downloaded Search & Replace and also Better Search Replace, and both plugins do not show a detailed report or location of where the product name is. I also need it to show where it occurs in every location beyond my posts (wp_posts), and I don't necessarily need to replace the name in my databases. Any suggestions? Does a plugin for this exists?

**Comment by schlessera** [comment]
GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
