### ISSUE TITLE
Run search-replace command in file

### ISSUE THREAD

**Issue by wespiremedia** [wp-cli/search-replace-command#15]
For me, it would be a great feature to run a search-replace command inside a file.

When I move a site from one server to another (assuming both servers are FTP only, no SSH access) I download the site + db to my local machine and upload both of them to the new server. 

To make replacements (for example when the site is a clone on another domainname), I have to import the sql dump into my own local database and setup a Wordpress installation, to be able to use the WP CLI search-replace command and create a new (rewrited) export. 

It would be a great feature to do search-replace replacements straight into a file. For example with a `--sql-file=` argument (the `--export=` argument should then also be required)

**Comment by danielbachhuber** [comment]
Hi @wespiremedia,

Thanks for the suggestion. This request is already tracked in https://github.com/wp-cli/ideas/issues/26
