### ISSUE TITLE
Short name

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/search-replace-command#17]
Could I add `@alias s-r`?

**Comment by gitlost** [comment]
Sounds reasonable to me.

**Comment by danielbachhuber** [comment]
We should use aliases sparingly because they can conflict with others commands.

You can use a bash alias for this.

**Comment by szepeviktor** [comment]
> We should use aliases sparingly

Could you imagine a new command named `s-r`?

**Comment by danielbachhuber** [comment]
> Could you imagine a new command named `s-r`?

In the world of all WP-CLI commands, it's possible that someone has done this.

From a product perspective, if we add an alias for one command, we should add aliases for other commands for consistency. Therefore, we'd need some policy around naming, etc.

Given there's a reasonable alternative (creating a bash alias), it makes sense to stick with the alternative for now.
