### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library

### ISSUE THREAD

**Issue by titanstitans** [wp-cli/search-replace-command#24]
The following modules are causing issue, even though they are enabled

[/]# wp search-replace 'http://xxx/wordpress/' 'http://xxx/' --all-tables
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/alt/php55/usr/lib64/php/modules/pspell.so' - libpspell.so.15: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/alt/php55/usr/lib64/php/modules/tidy.so' - libtidy-0.99.so.0: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/alt/php55/usr/lib64/php/modules/wddx.so' - /opt/alt/php55/usr/lib64/php/modules/wddx.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/alt/php55/usr/lib64/php/modules/xmlreader.so' - /opt/alt/php55/usr/lib64/php/modules/xmlreader.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/alt/php55/usr/lib64/php/modules/xmlrpc.so' - /opt/alt/php55/usr/lib64/php/modules/xmlrpc.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/alt/php55/usr/lib64/php/modules/xmlwriter.so' - /opt/alt/php55/usr/lib64/php/modules/xmlwriter.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/alt/php55/usr/lib64/php/modules/xsl.so' - /opt/alt/php55/usr/lib64/php/modules/xsl.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/alt/php55/usr/lib64/php/modules/zip.so' - /opt/alt/php55/usr/lib64/php/modules/zip.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0

 [/]# php -m
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/alt/php71/usr/lib64/php/modules/intl.so' - libicudata.so.57: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/alt/php71/usr/lib64/php/modules/pgsql.so' - /opt/alt/php71/usr/lib64/php/modules/pgsql.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/alt/php71/usr/lib64/php/modules/phar.so' - /opt/alt/php71/usr/lib64/php/modules/phar.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/alt/php71/usr/lib64/php/modules/pspell.so' - /opt/alt/php71/usr/lib64/php/modules/pspell.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/alt/php71/usr/lib64/php/modules/soap.so' - /opt/alt/php71/usr/lib64/php/modules/soap.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/alt/php71/usr/lib64/php/modules/sockets.so' - /opt/alt/php71/usr/lib64/php/modules/sockets.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/alt/php71/usr/lib64/php/modules/tidy.so' - /opt/alt/php71/usr/lib64/php/modules/tidy.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0

**Comment by schlessera** [comment]
@titanstitans This points to a problem with the PHP installation in your specific environment.

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
