### ISSUE TITLE
New feature: hide 0 changed results

### ISSUE THREAD

**Issue by raptor235** [wp-cli/search-replace-command#25]
Can we add an option to hide non changed results? When dealing with dbs that have 1000+ tables it becomes hard to filter which tables were affected.

**Comment by danielbachhuber** [comment]
👍 Seems reasonable.

`wp profile` has a `--spotlight` flag. I'd be amenable to adding the same to `wp search-replace`, which means the command would only output modifications.

**Comment by raptor235** [comment]
sounds perfect @danielbachhuber

**Comment by gitlost** [comment]
Via https://github.com/wp-cli/search-replace-command/pull/32 (as `--report-changed-only`).

**Comment by LC43** [comment]
Hi, noticed that `--report-changed-only` still shows "skipped" results. was this planned that way or is another way to hide these lines?
