### ISSUE TITLE
Option to exlude tables when using --all-tables

### ISSUE THREAD

**Issue by DRogueRonin** [wp-cli/search-replace-command#31]
I usually use `--export` to get a file that I can just import from dev to live. But as the development process can sometimes take some time, the live env does have new entries in some tables like the Gravity Forms Entry tables, that get overwritten on import.
So I'd just like to replace everything everywhere but export it to a file without the tables I don't want to have in the sql file.

Or maybe add an option to not include the tables, where nothing was replaced, in the exported file.

**Comment by danielbachhuber** [comment]
🔨
