### ISSUE TITLE
Multiple Search/Replaces

### ISSUE THREAD

**Issue by briankelleher** [wp-cli/search-replace-command#37]
Maybe I am missing something obvious, but I have not found a way to perform multiple search-replaces on a single database export file.  When generating an SQL export file from a staging or production instance to be used in any local environment, there often requires at least two search-replace operations (one for the domain, the second for the paths).

Does this functionality exist?  Or is it strictly limited to one search-replace?  I have found myself just writing more sed commands in the meantime to operate on the dumped file.  Is this within the scope of wp-cli search-replace?

**Comment by danielbachhuber** [comment]
If you could work out the correct regex, you could perform multiple search-replace with one incantation.

Otherwise, yes, you are correct: `wp search-replace` only supports one set at a time.

**Comment by noomz** [comment]
I don't agree that regex can perform multiple search-replace. WP data was serialized with PHP `serialize()` that has some meta, I mean, string length attached. If strings is modified but not the meta, then you cannot `unserialize()` them.
