### ISSUE TITLE
search-replace export breaking permalinks

### ISSUE THREAD

**Issue by davidegreenwald** [wp-cli/search-replace-command#44]
In testing `wp search-replace --export=database.sql`, I got some different results than using `wp db export database.sql` and then doing `wp search-replace` to the export later. Namely, in the `wp_options` table, the `--export` version breaks my permalinks:

> ('33', 'permalink_structure', '/{7267a97bdafb7aebecb895314b7351152b3b34ec93cfd83ec25869556c15d230}year{7267a97bdafb7aebecb895314b7351152b3b34ec93cfd83ec25869556c15d230}/{7267a97bdafb7aebecb895314b7351152b3b34ec93cfd83ec25869556c15d230}monthnum{7267a97bdafb7aebecb895314b7351152b3b34ec93cfd83ec25869556c15d230}/{7267a97bdafb7aebecb895314b7351152b3b34ec93cfd83ec25869556c15d230}postname{7267a97bdafb7aebecb895314b7351152b3b34ec93cfd83ec25869556c15d230}/', 'yes'),

When it should be:

> (33,'permalink_structure','/%year%/%monthnum%/%postname%/','yes')

So it appears the % characters are breaking the mysqldump. Any ideas?

**Comment by danielbachhuber** [comment]
Hi @davidegreenwald,

Can you share your WP-CLI version?

**Comment by davidegreenwald** [comment]
1.4.0. I'll upgrade and try again. I also noticed the `--export` dump made 30 changes to my URLs in wp_options, vs. making 19 with `export` + `search-replace` workflow, not sure if that's related. Happy to send over the sql dumps if that is helpful.
