### ISSUE TITLE
The report prints a message when the table's primary key isn't found

### ISSUE THREAD

**Issue by LC43** [wp-cli/search-replace-command#53]
Currently, when doing a search and replace with `--report-changed-only`, if the table has no primary key, it still prints the name of the table and the string 'skipped'.

It should only add to report when this flag isn't present.

example:

`wp search-replace 'aaaaaaaaa' 'bbbbbbb' --report-changed-only --url="example.com" --network `

will print:
```
+------------+--------+--------------+------+
| Table      | Column | Replacements | Type |
+------------+--------+--------------+------+
| wp_example |        | skipped      |      |
+------------+--------+--------------+------+

```

**Comment by marksabbath** [comment]
Should be fixed by https://github.com/wp-cli/search-replace-command/pull/54
