### ISSUE TITLE
Better error message on regex check.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/search-replace-command#66]
The regex check at [Search_Replace_Command.php#L191](https://github.com/wp-cli/search-replace-command/blob/v1.2.0/src/Search_Replace_Command.php#L191) just returns a `fails` message on false. It should return the PCRE error also, which can be got with `error_get_last()` (and confusingly not with `preg_last_error()`). Also sometimes gives an offset so it would be groovy to have it highlight or point to where in the regex that is.

Edit: maybe add this as a function in `Utils` as will be useful elsewhere also (eg `db search`).

**Comment by schlessera** [comment]
Fixed via #131
