### ISSUE TITLE
search-replace --regex line breaks not working

### ISSUE THREAD

**Issue by DuckDagobert** [wp-cli/search-replace-command#73]
when using:
wp search-replace "\r\n\r\n" "\r\n" --regex wp_posts --include-columns="post_content,post_excerpt"

it finds (matches) the double line breaks, but it will replace it with literal \r\n instead of line breaks.

**Comment by gitlost** [comment]
One way around it would be to do `wp search-replace "(\r\n)\r\n" "\1" --regex etc...`

**Comment by DuckDagobert** [comment]
thanks that works

**Comment by gitlost** [comment]
Although it would be handy it's probably not a good idea to support "\r" and "\n" escapes in the `new` string as it could cause all sorts of other issues so will close this...

**Comment by jerturowetz** [comment]
I'd like to request to reopen this issue. I think it's reasonable to expect regex expression support to be able to inject line breaks.
