### ISSUE TITLE
Allow changing database name

### ISSUE THREAD

**Issue by gitowiec** [wp-cli/search-replace-command#8]
Search-replace command could get option to let it work on other database than is read from WP configuration. When I do development I always have dev, staging and prod environments. Every one has its own domain, so running search-replace is a must. I often prepare databases for staging and prod on my dev machine. For example when my current Wordpress instance has db named wp_dbase I add two more dbs, its wp_dbase_staging and wp_dbase_prod. Then I copy wp_dbase -> wp_dbase_staging and run search and replace on wp_dbase_staging, Then it is prepared to upload on staging mysql server. Please consider additional option eg. --dbname=name_of_database_to_work_on

**Comment by danielbachhuber** [comment]
Do you know about `wp search-replace --export=<file>`?

```
[--export[=<file>]]
	Write transformed data as SQL file instead of saving replacements to
	the database. If <file> is not supplied, will output to STDOUT.
```

> Please consider additional option eg. --dbname=name_of_database_to_work_on

You can also easily perform this switch in your `wp-config.php`:

```
if ( defined( 'WP_CLI' ) && WP_CLI ) {
	define( 'DB_NAME', 'wp_dbase_staging' );
} else {
	define( 'DB_NAME', 'wp_dbase' );
}
```

**Comment by gitowiec** [comment]
Thank You for fast reply. I already was thinking about using `--export` with `search-replace` but `import` command does not have the option of changing current db. If I could export replaced INSERTs and import it back but to other database I wouldn't report this feature request :-)
Your second proposition is a little impeding, because all work I want to do with wp-cli should relate to wp_dbase (dev database). Only if I am done with changes and development I would like to perform export with search and replace to another db (I just thougth it would be awesome if wp-cli could upload replaced db to the server of one's choice eg `wp search-replace --export-ssh=current_project_staging_server_alias`)

**Comment by danielbachhuber** [comment]
> I already was thinking about using `--export` with `search-replace` but `impor`t command does not have the option of changing current db.

Couldn't you include the `DB_NAME` switch when running `wp db import` then? The SQL file doesn't have the database name in it, only the tables and SQL statements.

```
if ( defined( 'WP_CLI' ) && WP_CLI ) {
	define( 'DB_NAME', 'wp_dbase_staging' );
} else {
	define( 'DB_NAME', 'wp_dbase' );
}
```

**Comment by gitowiec** [comment]
Hmm do You mean `--require` a file which changes `DB_NAME` and put `require` directive into `wp-cli.yml` configuration for `import` command. I'm gonna check it out. I don't want to define DB_NAME according to if I run wp-cli in `wp-config.php` because if I would like to use eg. `wp plugin install` that would use staging database instead of development one.

**Comment by gitowiec** [comment]
Just found this, maybe it will do the thing... http://wp-sync-db.github.io/

**Comment by danielbachhuber** [comment]
I think this is out of scope for `wp search-replace`, which focuses on searching / replacing within WordPress database tables.

Good luck working out a workflow that works for you!
